#page title
page_title: "Last 10"

playstore_link: https://play.google.com/store/apps/details?id=dev.nery.last10&referrer=utm_source%3Dwebsite

app_icon: assets/appicon.png
app_name: "Last 10"
app_price: "Free"
app_description: "Your 10 last credit transactions in a tap"

enable_smart_app_banner: false

# Information About Yourself
your_name: Renan Nery
your_link: https://nery.dev
your_city: Cayman Islands
email_address: renannery@gmail.com
facebook_username:
instagram_username:
twitter_username:
github_username:
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Transactions
    description: Credit/Debit card can store the last 10 transactions in your card.
    fontawesome_icon_name: credit-card

  - title: NFC
    description: Last 10 uses the NFC scanner on your device in order to there these transactions. Normally they have the date amount, and currency.
    fontawesome_icon_name: mobile

  - title: Privacy
    description: The app isn't connect to the Internet, all your data won't be recorded or sent somewhere else.
    fontawesome_icon_name: shield-alt

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

body_background_color: "#ffffff"

link_color: "#FF6347"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#ffffff"
feature_icons_background_color: "#FF6347"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
